import { Metadata } from 'next';

import { Header } from './Header';
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: 'Welcome to join us!',
  description: 'Generated by Sanha Lee',
};

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Header />
      <main className={styles.main}>{children}</main>
    </>
  );
};

export default Layout;
