import type { Metadata } from 'next';

import './globals.css';
import { Provider } from './(client)/components';
import { combinedFontFamily } from './(client)/utils';

export const metadata: Metadata = {
  title: 'Next.js Project Template',
  description: 'Generated by Me',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body style={{ fontFamily: combinedFontFamily }}>
        <link rel='icon' href='/favicons/favicon.ico' sizes='any' />
        <div id='global-layout'>
          <Provider>{children}</Provider>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
